version: "3.9"

services:
  # Jaeger : L'outil de visualisation des traces
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Interface UI
      - "4317:4317"  # OTLP gRPC endpoint
      - "4318:4318"  # OTLP HTTP endpoint

  # FastAPI
  app:
    build: .
    ports:
      - "8001:8000"
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_SERVICE_NAME: "hr-pulse-backend"
    env_file:
      - .env
    depends_on:
      - jaeger
    volumes:
      - .:/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # service frontend 
  frontend:
    build: ../HR-Pulse-frontend

    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - app
    environment:
      NEXT_PUBLIC_API_URL: "http://app:8000"